# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExitDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exit(object):
    def setupUi(self, Exit):
        Exit.setObjectName("Exit")
        Exit.resize(1024, 496)
        Exit.setStyleSheet("QDialog{\n"
"    background-color: rgb(77, 77, 77);\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font: bold 30pt \"Open Sans\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: bold 30pt \"Open Sans\";\n"
"\n"
"    background-color: rgb(218, 28, 58);\n"
"    min-height: 200px;\n"
"    min-width: 200px;\n"
"\n"
"    border-radius: 30px;\n"
"    border-top: 1.5px solid  rgb(191, 21, 49);\n"
"    border-left: 3px solid  rgb(191, 21, 49);\n"
"    border-right: 3px solid  rgb(191, 21, 49);\n"
"    border-bottom: 4px solid  rgb(191, 21, 49);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(193, 21, 50);\n"
"    border-bottom:1.5px solid  rgb(136, 14, 35);\n"
"    border-left: 3px solid   rgb(136, 14, 35);\n"
"    border-right: 3px solid rgb(136, 14, 35);\n"
"    border-top: 4px solid rgb(136, 14, 35);\n"
" }")
        self.label = QtWidgets.QLabel(Exit)
        self.label.setGeometry(QtCore.QRect(0, 90, 1021, 81))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(Exit)
        self.buttonBox.setGeometry(QtCore.QRect(0, 210, 1021, 211))
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStyleSheet("margin-left: 60px;\n"
"margin-right: 60px;")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Exit)
        QtCore.QMetaObject.connectSlotsByName(Exit)

    def retranslateUi(self, Exit):
        _translate = QtCore.QCoreApplication.translate
        Exit.setWindowTitle(_translate("Exit", "Dialog"))
        self.label.setText(_translate("Exit", "​Are you sure you want to quit ShakeIt?​"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Exit = QtWidgets.QDialog()
    ui = Ui_Exit()
    ui.setupUi(Exit)
    Exit.show()
    sys.exit(app.exec_())
