# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1108, 618)
        Dialog.setStyleSheet("QDialog{\n"
"    background-color: rgb(72, 110, 176);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 30pt \"Open Sans\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(36, 55, 88);\n"
"    color: white;\n"
"    font: 30pt \"Open Sans\";\n"
"    min-height: 120px;\n"
"    min-width: 240px;\n"
"\n"
"    border-radius: 35px;\n"
"    border-top: 1px solid rgb(18, 28, 44);\n"
"    border-left: 1.5px solid  rgb(18, 28, 44);\n"
"    border-right: 1.5px solid  rgb(18, 28, 44);\n"
"    border-bottom: 2px solid rgb(18, 28, 44);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(18, 28, 44);\n"
"    border-top: 1px solid rgb(0, 0, 0);\n"
"    border-left: 1.5px solid  rgb(0,0,0);\n"
"    border-right: 1.5px solid  rgb(0,0,0);\n"
"    border-bottom: 2px solid rgb(0,0,0);\n"
" }")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 70, 1041, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: italic 32pt \"Open Sans\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 420, 1111, 151))
        self.buttonBox.setStyleSheet("margin-left: 60px;\n"
"margin-right: 60px;")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Interaction Information"))
        self.label_2.setText(_translate("Dialog", "You have 60 seconds to receive as many pickups as possible. Use different shakes to get the components into the correct position for a pick up."))
        self.label_3.setText(_translate("Dialog", "Ready to beat the AI’s score of 12 pickups?  "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
