# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InteractionUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interaction(object):
    def setupUi(self, Interaction):
        Interaction.setObjectName("Interaction")
        Interaction.resize(1920, 1080)
        Interaction.setMinimumSize(QtCore.QSize(1920, 1080))
        Interaction.setMaximumSize(QtCore.QSize(1920, 1080))
        self.stackedpages = QtWidgets.QStackedWidget(Interaction)
        self.stackedpages.setGeometry(QtCore.QRect(0, 0, 1921, 1081))
        self.stackedpages.setObjectName("stackedpages")
        self.page1welcome = QtWidgets.QWidget()
        self.page1welcome.setObjectName("page1welcome")
        self.label = QtWidgets.QLabel(self.page1welcome)
        self.label.setGeometry(QtCore.QRect(520, 240, 751, 191))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.buttonStart = QtWidgets.QPushButton(self.page1welcome)
        self.buttonStart.setGeometry(QtCore.QRect(690, 480, 321, 191))
        self.buttonStart.setObjectName("buttonStart")
        self.stackedpages.addWidget(self.page1welcome)
        self.page2try = QtWidgets.QWidget()
        self.page2try.setObjectName("page2try")
        self.label_2 = QtWidgets.QLabel(self.page2try)
        self.label_2.setGeometry(QtCore.QRect(640, 240, 531, 191))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.buttonReady = QtWidgets.QPushButton(self.page2try)
        self.buttonReady.setGeometry(QtCore.QRect(730, 520, 291, 141))
        self.buttonReady.setObjectName("buttonReady")
        self.stackedpages.addWidget(self.page2try)
        self.page3play = QtWidgets.QWidget()
        self.page3play.setObjectName("page3play")
        self.label_3 = QtWidgets.QLabel(self.page3play)
        self.label_3.setGeometry(QtCore.QRect(650, 200, 571, 191))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.buttonEnd = QtWidgets.QPushButton(self.page3play)
        self.buttonEnd.setGeometry(QtCore.QRect(770, 500, 271, 101))
        self.buttonEnd.setObjectName("buttonEnd")
        self.stackedpages.addWidget(self.page3play)
        self.page4board = QtWidgets.QWidget()
        self.page4board.setObjectName("page4board")
        self.label_4 = QtWidgets.QLabel(self.page4board)
        self.label_4.setGeometry(QtCore.QRect(620, 270, 681, 191))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.buttonExit = QtWidgets.QPushButton(self.page4board)
        self.buttonExit.setGeometry(QtCore.QRect(1700, 40, 161, 121))
        self.buttonExit.setObjectName("buttonExit")
        self.stackedpages.addWidget(self.page4board)

        self.retranslateUi(Interaction)
        QtCore.QMetaObject.connectSlotsByName(Interaction)

    def retranslateUi(self, Interaction):
        _translate = QtCore.QCoreApplication.translate
        Interaction.setWindowTitle(_translate("Interaction", "Form"))
        self.label.setText(_translate("Interaction", "page 1 Welcome"))
        self.buttonStart.setText(_translate("Interaction", "Start"))
        self.label_2.setText(_translate("Interaction", "page 2 Try"))
        self.buttonReady.setText(_translate("Interaction", "Ready to shake"))
        self.label_3.setText(_translate("Interaction", "page 3 play"))
        self.buttonEnd.setText(_translate("Interaction", "Times up"))
        self.label_4.setText(_translate("Interaction", " Player 4 board"))
        self.buttonExit.setText(_translate("Interaction", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Interaction = QtWidgets.QWidget()
    ui = Ui_Interaction()
    ui.setupUi(Interaction)
    Interaction.show()
    sys.exit(app.exec_())
