# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedLogin = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedLogin.setGeometry(QtCore.QRect(0, 0, 1921, 1081))
        self.stackedLogin.setStyleSheet("")
        self.stackedLogin.setObjectName("stackedLogin")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setStyleSheet("")
        self.loginPage.setObjectName("loginPage")
        self.background = QtWidgets.QLabel(self.loginPage)
        self.background.setGeometry(QtCore.QRect(0, 0, 1921, 1091))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("resources/backgroundlogin.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.frame = QtWidgets.QFrame(self.loginPage)
        self.frame.setGeometry(QtCore.QRect(700, 270, 531, 481))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.buttonLogin = QtWidgets.QPushButton(self.frame)
        self.buttonLogin.setGeometry(QtCore.QRect(90, 390, 341, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonLogin.setFont(font)
        self.buttonLogin.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"border-radius: 10px;\n"
"color: white")
        self.buttonLogin.setObjectName("buttonLogin")
        self.textPassword = QtWidgets.QLineEdit(self.frame)
        self.textPassword.setGeometry(QtCore.QRect(50, 280, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textPassword.setFont(font)
        self.textPassword.setStyleSheet("lineedit-password-character: 9679")
        self.textPassword.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textPassword.setMaxLength(32766)
        self.textPassword.setFrame(True)
        self.textPassword.setObjectName("textPassword")
        self.labelPassword = QtWidgets.QLabel(self.frame)
        self.labelPassword.setGeometry(QtCore.QRect(50, 240, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.labelPassword.setFont(font)
        self.labelPassword.setObjectName("labelPassword")
        self.textUsername = QtWidgets.QLineEdit(self.frame)
        self.textUsername.setGeometry(QtCore.QRect(50, 180, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textUsername.setFont(font)
        self.textUsername.setStyleSheet("")
        self.textUsername.setObjectName("textUsername")
        self.labelLoginError = QtWidgets.QLabel(self.frame)
        self.labelLoginError.setGeometry(QtCore.QRect(140, 339, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.labelLoginError.setFont(font)
        self.labelLoginError.setStyleSheet("color: rgb(206, 42, 42);")
        self.labelLoginError.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLoginError.setObjectName("labelLoginError")
        self.labelUsername = QtWidgets.QLabel(self.frame)
        self.labelUsername.setGeometry(QtCore.QRect(50, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.labelUsername.setFont(font)
        self.labelUsername.setObjectName("labelUsername")
        self.labelLogin = QtWidgets.QLabel(self.frame)
        self.labelLogin.setGeometry(QtCore.QRect(190, 40, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.labelLogin.setFont(font)
        self.labelLogin.setStyleSheet("color: rgb(255, 170, 127)")
        self.labelLogin.setObjectName("labelLogin")
        self.buttonLogin.raise_()
        self.labelPassword.raise_()
        self.labelLoginError.raise_()
        self.labelUsername.raise_()
        self.labelLogin.raise_()
        self.textUsername.raise_()
        self.textPassword.raise_()
        self.stackedLogin.addWidget(self.loginPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setStyleSheet("")
        self.mainPage.setObjectName("mainPage")
        self.stackedPages = QtWidgets.QStackedWidget(self.mainPage)
        self.stackedPages.setGeometry(QtCore.QRect(310, 0, 1611, 1081))
        self.stackedPages.setStyleSheet("")
        self.stackedPages.setObjectName("stackedPages")
        self.pageAI = QtWidgets.QWidget()
        self.pageAI.setStyleSheet("")
        self.pageAI.setObjectName("pageAI")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.pageAI)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(930, 150, 651, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Layoutstartstop = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Layoutstartstop.setContentsMargins(0, 0, 0, 0)
        self.Layoutstartstop.setSpacing(15)
        self.Layoutstartstop.setObjectName("Layoutstartstop")
        self.buttonStart = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonStart.setMaximumSize(QtCore.QSize(16777215, 200))
        self.buttonStart.setBaseSize(QtCore.QSize(0, 0))
        self.buttonStart.setStyleSheet("background-color:  rgb(127, 178, 133);\n"
"color: rgb(255, 255, 255);\n"
"font: 22pt \"Nirmala UI\";")
        self.buttonStart.setObjectName("buttonStart")
        self.Layoutstartstop.addWidget(self.buttonStart)
        self.buttonStop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonStop.setMaximumSize(QtCore.QSize(16777215, 200))
        self.buttonStop.setStyleSheet("background-color:rgb(199, 72, 72);\n"
"color: white;\n"
"font: 22pt \"Nirmala UI\";")
        self.buttonStop.setObjectName("buttonStop")
        self.Layoutstartstop.addWidget(self.buttonStop)
        self.Titel = QtWidgets.QLabel(self.pageAI)
        self.Titel.setGeometry(QtCore.QRect(40, 30, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Titel.setFont(font)
        self.Titel.setStyleSheet("font: 36pt \"Nirmala UI\";\n"
"color: white;")
        self.Titel.setObjectName("Titel")
        self.line = QtWidgets.QFrame(self.pageAI)
        self.line.setGeometry(QtCore.QRect(40, 100, 1541, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget = QtWidgets.QWidget(self.pageAI)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(510, 380, 1071, 641))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.graphlayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.graphlayout.setContentsMargins(0, 0, 0, 0)
        self.graphlayout.setObjectName("graphlayout")
        self.graph4 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graph4.setObjectName("graph4")
        self.graphlayout.addWidget(self.graph4, 1, 1, 1, 1)
        self.graph1 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graph1.setObjectName("graph1")
        self.graphlayout.addWidget(self.graph1, 0, 0, 1, 1)
        self.graph3 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graph3.setObjectName("graph3")
        self.graphlayout.addWidget(self.graph3, 1, 0, 1, 1)
        self.graph2 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graph2.setObjectName("graph2")
        self.graphlayout.addWidget(self.graph2, 0, 1, 1, 1)
        self.statusBox = QtWidgets.QGroupBox(self.pageAI)
        self.statusBox.setGeometry(QtCore.QRect(40, 140, 861, 211))
        self.statusBox.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: white;")
        self.statusBox.setObjectName("statusBox")
        self.settingsBox = QtWidgets.QGroupBox(self.pageAI)
        self.settingsBox.setGeometry(QtCore.QRect(40, 370, 431, 651))
        self.settingsBox.setStyleSheet("font: 75 18pt \"Nirmala UI\";\n"
"color: white;")
        self.settingsBox.setObjectName("settingsBox")
        self.buttonSettings = QtWidgets.QPushButton(self.settingsBox)
        self.buttonSettings.setGeometry(QtCore.QRect(110, 580, 211, 41))
        self.buttonSettings.setStyleSheet("font: 14pt \"Nirmala UI\";\n"
"background-color: rgb(93, 112, 131);\n"
"color: white;")
        self.buttonSettings.setObjectName("buttonSettings")
        self.spinIterations = QtWidgets.QSpinBox(self.settingsBox)
        self.spinIterations.setGeometry(QtCore.QRect(190, 60, 41, 31))
        self.spinIterations.setStyleSheet("color: black;\n"
"")
        self.spinIterations.setObjectName("spinIterations")
        self.labelIterations = QtWidgets.QLabel(self.settingsBox)
        self.labelIterations.setGeometry(QtCore.QRect(50, 60, 111, 31))
        self.labelIterations.setObjectName("labelIterations")
        self.backgroundAI = QtWidgets.QLabel(self.pageAI)
        self.backgroundAI.setGeometry(QtCore.QRect(0, 0, 1611, 1081))
        self.backgroundAI.setStyleSheet("background-color: #CE796B;")
        self.backgroundAI.setText("")
        self.backgroundAI.setObjectName("backgroundAI")
        self.backgroundAI.raise_()
        self.horizontalLayoutWidget.raise_()
        self.Titel.raise_()
        self.line.raise_()
        self.gridLayoutWidget.raise_()
        self.statusBox.raise_()
        self.settingsBox.raise_()
        self.stackedPages.addWidget(self.pageAI)
        self.pageManual = QtWidgets.QWidget()
        self.pageManual.setStyleSheet("QPushButton {\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.pageManual.setObjectName("pageManual")
        self.Titel_2 = QtWidgets.QLabel(self.pageManual)
        self.Titel_2.setGeometry(QtCore.QRect(40, 30, 671, 61))
        self.Titel_2.setStyleSheet("font: 36pt \"Nirmala UI\";\n"
"color: white;")
        self.Titel_2.setObjectName("Titel_2")
        self.line_2 = QtWidgets.QFrame(self.pageManual)
        self.line_2.setGeometry(QtCore.QRect(40, 100, 1541, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.pageManual)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 120, 1541, 901))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.layoutButtons = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.layoutButtons.setContentsMargins(0, 0, 0, 0)
        self.layoutButtons.setObjectName("layoutButtons")
        self.layoutForward = QtWidgets.QVBoxLayout()
        self.layoutForward.setSpacing(0)
        self.layoutForward.setObjectName("layoutForward")
        self.labelForward = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelForward.setMinimumSize(QtCore.QSize(0, 30))
        self.labelForward.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelForward.setStyleSheet("font: bold 20pt \"Nirmala UI\";\n"
"color: white;")
        self.labelForward.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForward.setObjectName("labelForward")
        self.layoutForward.addWidget(self.labelForward)
        self.fw_r1s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s2.setObjectName("fw_r1s2")
        self.layoutForward.addWidget(self.fw_r1s2)
        self.fw_r3s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s2.setObjectName("fw_r3s2")
        self.layoutForward.addWidget(self.fw_r3s2)
        self.fw_r1s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s4.setObjectName("fw_r1s4")
        self.layoutForward.addWidget(self.fw_r1s4)
        self.fw_r3s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s4.setObjectName("fw_r3s4")
        self.layoutForward.addWidget(self.fw_r3s4)
        self.fw_r1s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s6.setObjectName("fw_r1s6")
        self.layoutForward.addWidget(self.fw_r1s6)
        self.fw_r3s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s6.setObjectName("fw_r3s6")
        self.layoutForward.addWidget(self.fw_r3s6)
        self.fw_r1s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s8.setObjectName("fw_r1s8")
        self.layoutForward.addWidget(self.fw_r1s8)
        self.fw_r3s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s8.setObjectName("fw_r3s8")
        self.layoutForward.addWidget(self.fw_r3s8)
        self.fw_r1s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s10.setObjectName("fw_r1s10")
        self.layoutForward.addWidget(self.fw_r1s10)
        self.fw_r3s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s10.setObjectName("fw_r3s10")
        self.layoutForward.addWidget(self.fw_r3s10)
        self.layoutButtons.addLayout(self.layoutForward)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelBackward = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelBackward.setMinimumSize(QtCore.QSize(0, 30))
        self.labelBackward.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelBackward.setStyleSheet("font: bold 20pt \"Nirmala UI\";\n"
"color: white;")
        self.labelBackward.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBackward.setObjectName("labelBackward")
        self.verticalLayout_5.addWidget(self.labelBackward)
        self.b_r1s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s2.setObjectName("b_r1s2")
        self.verticalLayout_5.addWidget(self.b_r1s2)
        self.b_r3s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s2.setObjectName("b_r3s2")
        self.verticalLayout_5.addWidget(self.b_r3s2)
        self.b_r1s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s4.setObjectName("b_r1s4")
        self.verticalLayout_5.addWidget(self.b_r1s4)
        self.b_r3s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s4.setObjectName("b_r3s4")
        self.verticalLayout_5.addWidget(self.b_r3s4)
        self.b_r1s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s6.setObjectName("b_r1s6")
        self.verticalLayout_5.addWidget(self.b_r1s6)
        self.b_r3s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s6.setObjectName("b_r3s6")
        self.verticalLayout_5.addWidget(self.b_r3s6)
        self.b_r1s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s8.setObjectName("b_r1s8")
        self.verticalLayout_5.addWidget(self.b_r1s8)
        self.b_r3s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s8.setObjectName("b_r3s8")
        self.verticalLayout_5.addWidget(self.b_r3s8)
        self.b_r1s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s10.setObjectName("b_r1s10")
        self.verticalLayout_5.addWidget(self.b_r1s10)
        self.b_r3s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s10.setObjectName("b_r3s10")
        self.verticalLayout_5.addWidget(self.b_r3s10)
        self.layoutButtons.addLayout(self.verticalLayout_5)
        self.layoutFlip = QtWidgets.QVBoxLayout()
        self.layoutFlip.setSpacing(0)
        self.layoutFlip.setObjectName("layoutFlip")
        self.labelFlip = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelFlip.setMinimumSize(QtCore.QSize(0, 30))
        self.labelFlip.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelFlip.setStyleSheet("font: bold 20pt \"Nirmala UI\";\n"
"color: white;")
        self.labelFlip.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFlip.setObjectName("labelFlip")
        self.layoutFlip.addWidget(self.labelFlip)
        self.fp_r1s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s2.setObjectName("fp_r1s2")
        self.layoutFlip.addWidget(self.fp_r1s2)
        self.fp_r3s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s2.setObjectName("fp_r3s2")
        self.layoutFlip.addWidget(self.fp_r3s2)
        self.fp_r1s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s4.setObjectName("fp_r1s4")
        self.layoutFlip.addWidget(self.fp_r1s4)
        self.fp_r3s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s4.setObjectName("fp_r3s4")
        self.layoutFlip.addWidget(self.fp_r3s4)
        self.fp_r1s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s6.setObjectName("fp_r1s6")
        self.layoutFlip.addWidget(self.fp_r1s6)
        self.fp_r3s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s6.setObjectName("fp_r3s6")
        self.layoutFlip.addWidget(self.fp_r3s6)
        self.fp_r1s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s8.setObjectName("fp_r1s8")
        self.layoutFlip.addWidget(self.fp_r1s8)
        self.fp_r3s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s8.setObjectName("fp_r3s8")
        self.layoutFlip.addWidget(self.fp_r3s8)
        self.fp_r1s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s10.setObjectName("fp_r1s10")
        self.layoutFlip.addWidget(self.fp_r1s10)
        self.fp_r3s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s10.setObjectName("fp_r3s10")
        self.layoutFlip.addWidget(self.fp_r3s10)
        self.layoutButtons.addLayout(self.layoutFlip)
        self.backgroundManual = QtWidgets.QLabel(self.pageManual)
        self.backgroundManual.setGeometry(QtCore.QRect(0, 0, 1611, 1081))
        self.backgroundManual.setStyleSheet("background-color: #CE796B;")
        self.backgroundManual.setText("")
        self.backgroundManual.setObjectName("backgroundManual")
        self.backgroundManual.raise_()
        self.Titel_2.raise_()
        self.line_2.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.stackedPages.addWidget(self.pageManual)
        self.pageVS = QtWidgets.QWidget()
        self.pageVS.setStyleSheet("background-color: white;")
        self.pageVS.setObjectName("pageVS")
        self.backgroundVS = QtWidgets.QLabel(self.pageVS)
        self.backgroundVS.setGeometry(QtCore.QRect(0, 0, 1611, 1081))
        self.backgroundVS.setStyleSheet("background-color: #CE796B;")
        self.backgroundVS.setText("")
        self.backgroundVS.setObjectName("backgroundVS")
        self.stackedPages.addWidget(self.pageVS)
        self.buttonLogout = QtWidgets.QPushButton(self.mainPage)
        self.buttonLogout.setGeometry(QtCore.QRect(70, 960, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonLogout.setFont(font)
        self.buttonLogout.setStyleSheet("")
        self.buttonLogout.setObjectName("buttonLogout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.mainPage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 360, 221, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.buttonsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.buttonsLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.radioAI = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioAI.setStyleSheet("QRadioButton {\n"
"    font: 16pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  50px;\n"
"    height:                 50px;\n"
"    border-radius:          27px;\n"
"    image: url(resources/aiicon.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(206, 121, 107);\n"
"    border: 2px solid rgb(206, 121, 107);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: black;\n"
"    border: 2px solid;\n"
"}")
        self.radioAI.setObjectName("radioAI")
        self.buttonsLayout.addWidget(self.radioAI)
        self.radioManual = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioManual.setStyleSheet("QRadioButton {\n"
"    font: 16pt \"Nirmala UI\";\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  50px;\n"
"    height:                 50px;\n"
"    border-radius:          27px;\n"
"    image: url(resources/maunalicon.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(206, 121, 107);\n"
"    border: 2px solid rgb(206, 121, 107);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: black;\n"
"    border: 2px solid;\n"
"}")
        self.radioManual.setObjectName("radioManual")
        self.buttonsLayout.addWidget(self.radioManual)
        self.radioVS = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioVS.setStyleSheet("QRadioButton {\n"
"    font: 16pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  50px;\n"
"    height:                 50px;\n"
"    border-radius:          27px;\n"
"    image: url(resources/vsicon.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(206, 121, 107);\n"
"    border: 2px solid rgb(206, 121, 107);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: black;\n"
"    border: 2px solid;\n"
"}")
        self.radioVS.setObjectName("radioVS")
        self.buttonsLayout.addWidget(self.radioVS)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.mainPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 220, 221, 59))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.userInfoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.userInfoLayout.setContentsMargins(0, 0, 0, 0)
        self.userInfoLayout.setSpacing(0)
        self.userInfoLayout.setObjectName("userInfoLayout")
        self.labelRole = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelRole.setStyleSheet("font: 14pt \"Nirmala UI\";\n"
"color: rgb(93, 93, 93);")
        self.labelRole.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRole.setObjectName("labelRole")
        self.userInfoLayout.addWidget(self.labelRole)
        self.labelUsername_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelUsername_2.setStyleSheet("font: 18pt \"Nirmala UI\";")
        self.labelUsername_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUsername_2.setObjectName("labelUsername_2")
        self.userInfoLayout.addWidget(self.labelUsername_2)
        self.sidebarBackground = QtWidgets.QLabel(self.mainPage)
        self.sidebarBackground.setGeometry(QtCore.QRect(0, 0, 311, 1081))
        self.sidebarBackground.setStyleSheet("background-color: #E7AD99;")
        self.sidebarBackground.setText("")
        self.sidebarBackground.setScaledContents(False)
        self.sidebarBackground.setObjectName("sidebarBackground")
        self.label = QtWidgets.QLabel(self.mainPage)
        self.label.setGeometry(QtCore.QRect(80, 80, 151, 121))
        self.label.setStyleSheet("image: url(resources/usericon.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.sidebarBackground.raise_()
        self.stackedPages.raise_()
        self.buttonLogout.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.label.raise_()
        self.stackedLogin.addWidget(self.mainPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedLogin.setCurrentIndex(1)
        self.stackedPages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textUsername, self.textPassword)
        MainWindow.setTabOrder(self.textPassword, self.buttonLogin)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonLogin.setText(_translate("MainWindow", "Log in"))
        self.labelPassword.setText(_translate("MainWindow", "Password"))
        self.labelLoginError.setText(_translate("MainWindow", "Invalid username or password"))
        self.labelUsername.setText(_translate("MainWindow", "Username"))
        self.labelLogin.setText(_translate("MainWindow", "Log in"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.buttonStop.setText(_translate("MainWindow", "Stop"))
        self.Titel.setText(_translate("MainWindow", "Shakeit AI Control Panel"))
        self.statusBox.setTitle(_translate("MainWindow", "Status"))
        self.settingsBox.setTitle(_translate("MainWindow", "Setttings"))
        self.buttonSettings.setText(_translate("MainWindow", "Change settings"))
        self.labelIterations.setText(_translate("MainWindow", "Iterations:"))
        self.Titel_2.setText(_translate("MainWindow", "Shakeit Manual Control Panel"))
        self.labelForward.setText(_translate("MainWindow", "Forward"))
        self.fw_r1s2.setText(_translate("MainWindow", "Repetitions:1, Speed: 2"))
        self.fw_r3s2.setText(_translate("MainWindow", "Repetitions:3, Speed: 2"))
        self.fw_r1s4.setText(_translate("MainWindow", "Repetitions:1, Speed: 4"))
        self.fw_r3s4.setText(_translate("MainWindow", "Repetitions:3, Speed: 4"))
        self.fw_r1s6.setText(_translate("MainWindow", "Repetitions:1, Speed: 6"))
        self.fw_r3s6.setText(_translate("MainWindow", "Repetitions:3, Speed: 6"))
        self.fw_r1s8.setText(_translate("MainWindow", "Repetitions:1, Speed: 8"))
        self.fw_r3s8.setText(_translate("MainWindow", "Repetitions:3, Speed: 8"))
        self.fw_r1s10.setText(_translate("MainWindow", "Repetitions:1, Speed: 10"))
        self.fw_r3s10.setText(_translate("MainWindow", "Repetitions:3, Speed: 10"))
        self.labelBackward.setText(_translate("MainWindow", "Backward"))
        self.b_r1s2.setText(_translate("MainWindow", "Repetitions:1, Speed: 2"))
        self.b_r3s2.setText(_translate("MainWindow", "Repetitions:3, Speed: 2"))
        self.b_r1s4.setText(_translate("MainWindow", "Repetitions:1, Speed: 4"))
        self.b_r3s4.setText(_translate("MainWindow", "Repetitions:3, Speed: 4"))
        self.b_r1s6.setText(_translate("MainWindow", "Repetitions:1, Speed: 6"))
        self.b_r3s6.setText(_translate("MainWindow", "Repetitions:3, Speed: 6"))
        self.b_r1s8.setText(_translate("MainWindow", "Repetitions:1, Speed: 8"))
        self.b_r3s8.setText(_translate("MainWindow", "Repetitions:3, Speed: 8"))
        self.b_r1s10.setText(_translate("MainWindow", "Repetitions:1, Speed: 10"))
        self.b_r3s10.setText(_translate("MainWindow", "Repetitions:3, Speed: 10"))
        self.labelFlip.setText(_translate("MainWindow", "Flip"))
        self.fp_r1s2.setText(_translate("MainWindow", "Repetitions:1, Speed: 2"))
        self.fp_r3s2.setText(_translate("MainWindow", "Repetitions:3, Speed: 2"))
        self.fp_r1s4.setText(_translate("MainWindow", "Repetitions:1, Speed: 4"))
        self.fp_r3s4.setText(_translate("MainWindow", "Repetitions:3, Speed: 4"))
        self.fp_r1s6.setText(_translate("MainWindow", "Repetitions:1, Speed: 6"))
        self.fp_r3s6.setText(_translate("MainWindow", "Repetitions:3, Speed: 6"))
        self.fp_r1s8.setText(_translate("MainWindow", "Repetitions:1, Speed: 8"))
        self.fp_r3s8.setText(_translate("MainWindow", "Repetitions:3, Speed: 8"))
        self.fp_r1s10.setText(_translate("MainWindow", "Repetitions:1, Speed: 10"))
        self.fp_r3s10.setText(_translate("MainWindow", "Repetitions:3, Speed: 10"))
        self.buttonLogout.setText(_translate("MainWindow", "Log out"))
        self.radioAI.setText(_translate("MainWindow", " AI Control"))
        self.radioManual.setText(_translate("MainWindow", "Manual Control"))
        self.radioVS.setText(_translate("MainWindow", "Manual vs AI"))
        self.labelRole.setText(_translate("MainWindow", "Role"))
        self.labelUsername_2.setText(_translate("MainWindow", "Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
