# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1050)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1050))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1050))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedLogin = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedLogin.setGeometry(QtCore.QRect(0, 0, 1921, 1081))
        self.stackedLogin.setStyleSheet("")
        self.stackedLogin.setObjectName("stackedLogin")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setStyleSheet("")
        self.loginPage.setObjectName("loginPage")
        self.background = QtWidgets.QLabel(self.loginPage)
        self.background.setGeometry(QtCore.QRect(0, 0, 1921, 1091))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("resources/backgroundlogin.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.frame = QtWidgets.QFrame(self.loginPage)
        self.frame.setGeometry(QtCore.QRect(700, 270, 531, 481))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.buttonLogin = QtWidgets.QPushButton(self.frame)
        self.buttonLogin.setGeometry(QtCore.QRect(90, 390, 341, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonLogin.setFont(font)
        self.buttonLogin.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"border-radius: 10px;\n"
"color: white")
        self.buttonLogin.setObjectName("buttonLogin")
        self.textPassword = QtWidgets.QLineEdit(self.frame)
        self.textPassword.setGeometry(QtCore.QRect(50, 280, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textPassword.setFont(font)
        self.textPassword.setStyleSheet("lineedit-password-character: 9679")
        self.textPassword.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textPassword.setMaxLength(32766)
        self.textPassword.setFrame(True)
        self.textPassword.setObjectName("textPassword")
        self.labelPassword = QtWidgets.QLabel(self.frame)
        self.labelPassword.setGeometry(QtCore.QRect(50, 240, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.labelPassword.setFont(font)
        self.labelPassword.setObjectName("labelPassword")
        self.textUsername = QtWidgets.QLineEdit(self.frame)
        self.textUsername.setGeometry(QtCore.QRect(50, 180, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textUsername.setFont(font)
        self.textUsername.setStyleSheet("")
        self.textUsername.setObjectName("textUsername")
        self.labelLoginError = QtWidgets.QLabel(self.frame)
        self.labelLoginError.setGeometry(QtCore.QRect(130, 340, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.labelLoginError.setFont(font)
        self.labelLoginError.setStyleSheet("color: rgb(206, 42, 42);")
        self.labelLoginError.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLoginError.setObjectName("labelLoginError")
        self.labelUsername = QtWidgets.QLabel(self.frame)
        self.labelUsername.setGeometry(QtCore.QRect(50, 140, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.labelUsername.setFont(font)
        self.labelUsername.setObjectName("labelUsername")
        self.labelLogin = QtWidgets.QLabel(self.frame)
        self.labelLogin.setGeometry(QtCore.QRect(180, 40, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.labelLogin.setFont(font)
        self.labelLogin.setStyleSheet("color: rgb(255, 170, 127)")
        self.labelLogin.setObjectName("labelLogin")
        self.buttonLogin.raise_()
        self.labelPassword.raise_()
        self.labelLoginError.raise_()
        self.labelUsername.raise_()
        self.labelLogin.raise_()
        self.textUsername.raise_()
        self.textPassword.raise_()
        self.stackedLogin.addWidget(self.loginPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setStyleSheet("")
        self.mainPage.setObjectName("mainPage")
        self.stackedPages = QtWidgets.QStackedWidget(self.mainPage)
        self.stackedPages.setGeometry(QtCore.QRect(310, 0, 1611, 1081))
        self.stackedPages.setStyleSheet(".pagebackground{\n"
"    background-color: #CE796B;\n"
"}")
        self.stackedPages.setObjectName("stackedPages")
        self.pageAI = QtWidgets.QWidget()
        self.pageAI.setStyleSheet("")
        self.pageAI.setObjectName("pageAI")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.pageAI)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(930, 150, 651, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Layoutstartstop = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Layoutstartstop.setContentsMargins(0, 0, 0, 0)
        self.Layoutstartstop.setSpacing(15)
        self.Layoutstartstop.setObjectName("Layoutstartstop")
        self.buttonStart = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonStart.setMaximumSize(QtCore.QSize(16777215, 200))
        self.buttonStart.setBaseSize(QtCore.QSize(0, 0))
        self.buttonStart.setStyleSheet("background-color:  rgb(127, 178, 133);\n"
"color: rgb(255, 255, 255);\n"
"font: 22pt \"Nirmala UI\";")
        self.buttonStart.setObjectName("buttonStart")
        self.Layoutstartstop.addWidget(self.buttonStart)
        self.buttonStop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonStop.setMaximumSize(QtCore.QSize(16777215, 200))
        self.buttonStop.setStyleSheet("background-color:rgb(199, 72, 72);\n"
"color: white;\n"
"font: 22pt \"Nirmala UI\";")
        self.buttonStop.setObjectName("buttonStop")
        self.Layoutstartstop.addWidget(self.buttonStop)
        self.Titel = QtWidgets.QLabel(self.pageAI)
        self.Titel.setGeometry(QtCore.QRect(40, 30, 641, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Titel.setFont(font)
        self.Titel.setStyleSheet("font: 36pt \"Nirmala UI\";\n"
"color: white;")
        self.Titel.setObjectName("Titel")
        self.line = QtWidgets.QFrame(self.pageAI)
        self.line.setGeometry(QtCore.QRect(40, 100, 1541, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget = QtWidgets.QWidget(self.pageAI)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(510, 380, 1071, 641))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.graphlayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.graphlayout.setContentsMargins(0, 0, 0, 0)
        self.graphlayout.setObjectName("graphlayout")
        self.graph4 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graph4.setObjectName("graph4")
        self.graphlayout.addWidget(self.graph4, 1, 1, 1, 1)
        self.graph1 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graph1.setObjectName("graph1")
        self.graphlayout.addWidget(self.graph1, 0, 0, 1, 1)
        self.graph3 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graph3.setObjectName("graph3")
        self.graphlayout.addWidget(self.graph3, 1, 0, 1, 1)
        self.graph2 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graph2.setObjectName("graph2")
        self.graphlayout.addWidget(self.graph2, 0, 1, 1, 1)
        self.statusBox = QtWidgets.QGroupBox(self.pageAI)
        self.statusBox.setGeometry(QtCore.QRect(40, 140, 861, 211))
        self.statusBox.setStyleSheet("font: 18pt \"Nirmala UI\";\n"
"color: white;")
        self.statusBox.setObjectName("statusBox")
        self.settingsBox = QtWidgets.QGroupBox(self.pageAI)
        self.settingsBox.setGeometry(QtCore.QRect(40, 370, 431, 651))
        self.settingsBox.setStyleSheet("font: 75 18pt \"Nirmala UI\";\n"
"color: white;")
        self.settingsBox.setObjectName("settingsBox")
        self.buttonSettings = QtWidgets.QPushButton(self.settingsBox)
        self.buttonSettings.setGeometry(QtCore.QRect(110, 580, 211, 41))
        self.buttonSettings.setStyleSheet("font: 14pt \"Nirmala UI\";\n"
"background-color: rgb(93, 112, 131);\n"
"color: white;")
        self.buttonSettings.setObjectName("buttonSettings")
        self.spinIterations = QtWidgets.QSpinBox(self.settingsBox)
        self.spinIterations.setGeometry(QtCore.QRect(190, 60, 41, 31))
        self.spinIterations.setStyleSheet("color: black;\n"
"")
        self.spinIterations.setObjectName("spinIterations")
        self.labelIterations = QtWidgets.QLabel(self.settingsBox)
        self.labelIterations.setGeometry(QtCore.QRect(50, 60, 131, 31))
        self.labelIterations.setObjectName("labelIterations")
        self.aibackground = QtWidgets.QLabel(self.pageAI)
        self.aibackground.setGeometry(QtCore.QRect(0, 0, 1611, 1081))
        self.aibackground.setStyleSheet("background-color: rgb(206, 121, 107);")
        self.aibackground.setText("")
        self.aibackground.setObjectName("aibackground")
        self.aibackground.raise_()
        self.horizontalLayoutWidget.raise_()
        self.Titel.raise_()
        self.line.raise_()
        self.gridLayoutWidget.raise_()
        self.statusBox.raise_()
        self.settingsBox.raise_()
        self.stackedPages.addWidget(self.pageAI)
        self.pageManual = QtWidgets.QWidget()
        self.pageManual.setStyleSheet("QPushButton {\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.pageManual.setObjectName("pageManual")
        self.Titel_2 = QtWidgets.QLabel(self.pageManual)
        self.Titel_2.setGeometry(QtCore.QRect(40, 30, 711, 61))
        self.Titel_2.setStyleSheet("font: 36pt \"Nirmala UI\";\n"
"color: white;")
        self.Titel_2.setObjectName("Titel_2")
        self.line_2 = QtWidgets.QFrame(self.pageManual)
        self.line_2.setGeometry(QtCore.QRect(40, 100, 1541, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.pageManual)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 120, 1541, 901))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.layoutButtons = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.layoutButtons.setContentsMargins(0, 0, 0, 0)
        self.layoutButtons.setObjectName("layoutButtons")
        self.layoutForward = QtWidgets.QVBoxLayout()
        self.layoutForward.setSpacing(0)
        self.layoutForward.setObjectName("layoutForward")
        self.labelForward = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelForward.setMinimumSize(QtCore.QSize(0, 30))
        self.labelForward.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelForward.setStyleSheet("font: bold 20pt \"Nirmala UI\";\n"
"color: white;")
        self.labelForward.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForward.setObjectName("labelForward")
        self.layoutForward.addWidget(self.labelForward)
        self.fw_r1s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s2.setObjectName("fw_r1s2")
        self.layoutForward.addWidget(self.fw_r1s2)
        self.fw_r3s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s2.setObjectName("fw_r3s2")
        self.layoutForward.addWidget(self.fw_r3s2)
        self.fw_r1s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s4.setObjectName("fw_r1s4")
        self.layoutForward.addWidget(self.fw_r1s4)
        self.fw_r3s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s4.setObjectName("fw_r3s4")
        self.layoutForward.addWidget(self.fw_r3s4)
        self.fw_r1s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s6.setObjectName("fw_r1s6")
        self.layoutForward.addWidget(self.fw_r1s6)
        self.fw_r3s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s6.setObjectName("fw_r3s6")
        self.layoutForward.addWidget(self.fw_r3s6)
        self.fw_r1s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s8.setObjectName("fw_r1s8")
        self.layoutForward.addWidget(self.fw_r1s8)
        self.fw_r3s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s8.setObjectName("fw_r3s8")
        self.layoutForward.addWidget(self.fw_r3s8)
        self.fw_r1s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r1s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r1s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r1s10.setObjectName("fw_r1s10")
        self.layoutForward.addWidget(self.fw_r1s10)
        self.fw_r3s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fw_r3s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fw_r3s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fw_r3s10.setObjectName("fw_r3s10")
        self.layoutForward.addWidget(self.fw_r3s10)
        self.layoutButtons.addLayout(self.layoutForward)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelBackward = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelBackward.setMinimumSize(QtCore.QSize(0, 30))
        self.labelBackward.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelBackward.setStyleSheet("font: bold 20pt \"Nirmala UI\";\n"
"color: white;")
        self.labelBackward.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBackward.setObjectName("labelBackward")
        self.verticalLayout_5.addWidget(self.labelBackward)
        self.b_r1s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s2.setObjectName("b_r1s2")
        self.verticalLayout_5.addWidget(self.b_r1s2)
        self.b_r3s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s2.setObjectName("b_r3s2")
        self.verticalLayout_5.addWidget(self.b_r3s2)
        self.b_r1s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s4.setObjectName("b_r1s4")
        self.verticalLayout_5.addWidget(self.b_r1s4)
        self.b_r3s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s4.setObjectName("b_r3s4")
        self.verticalLayout_5.addWidget(self.b_r3s4)
        self.b_r1s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s6.setObjectName("b_r1s6")
        self.verticalLayout_5.addWidget(self.b_r1s6)
        self.b_r3s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s6.setObjectName("b_r3s6")
        self.verticalLayout_5.addWidget(self.b_r3s6)
        self.b_r1s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s8.setObjectName("b_r1s8")
        self.verticalLayout_5.addWidget(self.b_r1s8)
        self.b_r3s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s8.setObjectName("b_r3s8")
        self.verticalLayout_5.addWidget(self.b_r3s8)
        self.b_r1s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r1s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r1s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r1s10.setObjectName("b_r1s10")
        self.verticalLayout_5.addWidget(self.b_r1s10)
        self.b_r3s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_r3s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.b_r3s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.b_r3s10.setObjectName("b_r3s10")
        self.verticalLayout_5.addWidget(self.b_r3s10)
        self.layoutButtons.addLayout(self.verticalLayout_5)
        self.layoutFlip = QtWidgets.QVBoxLayout()
        self.layoutFlip.setSpacing(0)
        self.layoutFlip.setObjectName("layoutFlip")
        self.labelFlip = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelFlip.setMinimumSize(QtCore.QSize(0, 30))
        self.labelFlip.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelFlip.setStyleSheet("font: bold 20pt \"Nirmala UI\";\n"
"color: white;")
        self.labelFlip.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFlip.setObjectName("labelFlip")
        self.layoutFlip.addWidget(self.labelFlip)
        self.fp_r1s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s2.setObjectName("fp_r1s2")
        self.layoutFlip.addWidget(self.fp_r1s2)
        self.fp_r3s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s2.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s2.setObjectName("fp_r3s2")
        self.layoutFlip.addWidget(self.fp_r3s2)
        self.fp_r1s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s4.setObjectName("fp_r1s4")
        self.layoutFlip.addWidget(self.fp_r1s4)
        self.fp_r3s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s4.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s4.setObjectName("fp_r3s4")
        self.layoutFlip.addWidget(self.fp_r3s4)
        self.fp_r1s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s6.setObjectName("fp_r1s6")
        self.layoutFlip.addWidget(self.fp_r1s6)
        self.fp_r3s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s6.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s6.setObjectName("fp_r3s6")
        self.layoutFlip.addWidget(self.fp_r3s6)
        self.fp_r1s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s8.setObjectName("fp_r1s8")
        self.layoutFlip.addWidget(self.fp_r1s8)
        self.fp_r3s8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s8.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s8.setObjectName("fp_r3s8")
        self.layoutFlip.addWidget(self.fp_r3s8)
        self.fp_r1s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r1s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r1s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r1s10.setObjectName("fp_r1s10")
        self.layoutFlip.addWidget(self.fp_r1s10)
        self.fp_r3s10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fp_r3s10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fp_r3s10.setStyleSheet("QPushButton {\n"
"    min-height: 60 px;\n"
"    background-color: rgb(93, 112, 131);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"    color: rgb(226, 234, 216);\n"
"    border-left: 1px sold  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(112, 133, 153);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-bottom: 3px solid  rgb(73, 88, 103);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(76, 92, 107);\n"
"    border-left: 1px solid  rgb(73, 88, 103);\n"
"    border-right: 1px solid  rgb(73, 88, 103);\n"
"    border-top: 3px solid  rgb(73, 88, 103);\n"
"    padding-top: -5px;\n"
"    border-bottom: none;\n"
"}")
        self.fp_r3s10.setObjectName("fp_r3s10")
        self.layoutFlip.addWidget(self.fp_r3s10)
        self.layoutButtons.addLayout(self.layoutFlip)
        self.stackedPages.addWidget(self.pageManual)
        self.pageBoard = QtWidgets.QWidget()
        self.pageBoard.setStyleSheet(".board_num{\n"
"    background-color: rgb(40, 85, 162);\n"
"    color: rgb(255, 255, 255);\n"
"    min-width: 100px;\n"
"    max-width: 100px;\n"
"    min-height: 100px;\n"
"    max-height: 100px;\n"
"    border-radius: 50px;\n"
"    font: bold 26pt \"Open Sans\";\n"
"    margin: 10px;\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 22pt \"Open Sans\";\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pageBoard.setObjectName("pageBoard")
        self.Titel_3 = QtWidgets.QLabel(self.pageBoard)
        self.Titel_3.setGeometry(QtCore.QRect(40, 30, 711, 61))
        self.Titel_3.setStyleSheet("font: 36pt \"Nirmala UI\";\n"
"color: white;")
        self.Titel_3.setObjectName("Titel_3")
        self.line_23 = QtWidgets.QFrame(self.pageBoard)
        self.line_23.setGeometry(QtCore.QRect(40, 100, 1541, 16))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.layoutWidget = QtWidgets.QWidget(self.pageBoard)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 160, 1201, 821))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.horizontalLayout7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout7.setObjectName("horizontalLayout7")
        self.num7 = QtWidgets.QLabel(self.layoutWidget)
        self.num7.setStyleSheet("")
        self.num7.setAlignment(QtCore.Qt.AlignCenter)
        self.num7.setObjectName("num7")
        self.horizontalLayout7.addWidget(self.num7)
        self.verticalLayout7 = QtWidgets.QVBoxLayout()
        self.verticalLayout7.setSpacing(0)
        self.verticalLayout7.setObjectName("verticalLayout7")
        self.name7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name7.sizePolicy().hasHeightForWidth())
        self.name7.setSizePolicy(sizePolicy)
        self.name7.setStyleSheet("")
        self.name7.setText("")
        self.name7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name7.setObjectName("name7")
        self.verticalLayout7.addWidget(self.name7)
        self.pickups7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups7.sizePolicy().hasHeightForWidth())
        self.pickups7.setSizePolicy(sizePolicy)
        self.pickups7.setStyleSheet("")
        self.pickups7.setText("")
        self.pickups7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups7.setObjectName("pickups7")
        self.verticalLayout7.addWidget(self.pickups7)
        self.line7 = QtWidgets.QFrame(self.layoutWidget)
        self.line7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line7.setObjectName("line7")
        self.verticalLayout7.addWidget(self.line7)
        self.horizontalLayout7.addLayout(self.verticalLayout7)
        self.gridLayout_4.addLayout(self.horizontalLayout7, 1, 2, 1, 1)
        self.horizontalLayout9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout9.setObjectName("horizontalLayout9")
        self.num9 = QtWidgets.QLabel(self.layoutWidget)
        self.num9.setStyleSheet("")
        self.num9.setAlignment(QtCore.Qt.AlignCenter)
        self.num9.setObjectName("num9")
        self.horizontalLayout9.addWidget(self.num9)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.name9 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name9.sizePolicy().hasHeightForWidth())
        self.name9.setSizePolicy(sizePolicy)
        self.name9.setStyleSheet("")
        self.name9.setText("")
        self.name9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name9.setObjectName("name9")
        self.verticalLayout_21.addWidget(self.name9)
        self.pickups9 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups9.sizePolicy().hasHeightForWidth())
        self.pickups9.setSizePolicy(sizePolicy)
        self.pickups9.setStyleSheet("")
        self.pickups9.setText("")
        self.pickups9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups9.setObjectName("pickups9")
        self.verticalLayout_21.addWidget(self.pickups9)
        self.line9 = QtWidgets.QFrame(self.layoutWidget)
        self.line9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line9.setObjectName("line9")
        self.verticalLayout_21.addWidget(self.line9)
        self.horizontalLayout9.addLayout(self.verticalLayout_21)
        self.gridLayout_4.addLayout(self.horizontalLayout9, 3, 2, 1, 1)
        self.horizontalLayout8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout8.setObjectName("horizontalLayout8")
        self.num8 = QtWidgets.QLabel(self.layoutWidget)
        self.num8.setStyleSheet("")
        self.num8.setAlignment(QtCore.Qt.AlignCenter)
        self.num8.setObjectName("num8")
        self.horizontalLayout8.addWidget(self.num8)
        self.verticalLayout8 = QtWidgets.QVBoxLayout()
        self.verticalLayout8.setSpacing(0)
        self.verticalLayout8.setObjectName("verticalLayout8")
        self.name8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name8.sizePolicy().hasHeightForWidth())
        self.name8.setSizePolicy(sizePolicy)
        self.name8.setStyleSheet("")
        self.name8.setText("")
        self.name8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name8.setObjectName("name8")
        self.verticalLayout8.addWidget(self.name8)
        self.pickups8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups8.sizePolicy().hasHeightForWidth())
        self.pickups8.setSizePolicy(sizePolicy)
        self.pickups8.setStyleSheet("")
        self.pickups8.setText("")
        self.pickups8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups8.setObjectName("pickups8")
        self.verticalLayout8.addWidget(self.pickups8)
        self.line8 = QtWidgets.QFrame(self.layoutWidget)
        self.line8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line8.setObjectName("line8")
        self.verticalLayout8.addWidget(self.line8)
        self.horizontalLayout8.addLayout(self.verticalLayout8)
        self.gridLayout_4.addLayout(self.horizontalLayout8, 2, 2, 1, 1)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.num2 = QtWidgets.QLabel(self.layoutWidget)
        self.num2.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.num2.setAlignment(QtCore.Qt.AlignCenter)
        self.num2.setObjectName("num2")
        self.horizontalLayout2.addWidget(self.num2)
        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setSpacing(0)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.name2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name2.sizePolicy().hasHeightForWidth())
        self.name2.setSizePolicy(sizePolicy)
        self.name2.setStyleSheet("")
        self.name2.setText("")
        self.name2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name2.setObjectName("name2")
        self.verticalLayout2.addWidget(self.name2)
        self.pickups2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups2.sizePolicy().hasHeightForWidth())
        self.pickups2.setSizePolicy(sizePolicy)
        self.pickups2.setStyleSheet("")
        self.pickups2.setText("")
        self.pickups2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups2.setObjectName("pickups2")
        self.verticalLayout2.addWidget(self.pickups2)
        self.line2 = QtWidgets.QFrame(self.layoutWidget)
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.verticalLayout2.addWidget(self.line2)
        self.horizontalLayout2.addLayout(self.verticalLayout2)
        self.gridLayout_4.addLayout(self.horizontalLayout2, 1, 0, 1, 1)
        self.horizontalLayout5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.num5 = QtWidgets.QLabel(self.layoutWidget)
        self.num5.setStyleSheet("")
        self.num5.setAlignment(QtCore.Qt.AlignCenter)
        self.num5.setObjectName("num5")
        self.horizontalLayout5.addWidget(self.num5)
        self.verticalLayout5 = QtWidgets.QVBoxLayout()
        self.verticalLayout5.setSpacing(0)
        self.verticalLayout5.setObjectName("verticalLayout5")
        self.name5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name5.sizePolicy().hasHeightForWidth())
        self.name5.setSizePolicy(sizePolicy)
        self.name5.setStyleSheet("")
        self.name5.setText("")
        self.name5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name5.setObjectName("name5")
        self.verticalLayout5.addWidget(self.name5)
        self.pickups5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups5.sizePolicy().hasHeightForWidth())
        self.pickups5.setSizePolicy(sizePolicy)
        self.pickups5.setStyleSheet("")
        self.pickups5.setText("")
        self.pickups5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups5.setObjectName("pickups5")
        self.verticalLayout5.addWidget(self.pickups5)
        self.line5 = QtWidgets.QFrame(self.layoutWidget)
        self.line5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line5.setObjectName("line5")
        self.verticalLayout5.addWidget(self.line5)
        self.horizontalLayout5.addLayout(self.verticalLayout5)
        self.gridLayout_4.addLayout(self.horizontalLayout5, 4, 0, 1, 1)
        self.horizontalLayout10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout10.setObjectName("horizontalLayout10")
        self.num10 = QtWidgets.QLabel(self.layoutWidget)
        self.num10.setStyleSheet("")
        self.num10.setAlignment(QtCore.Qt.AlignCenter)
        self.num10.setObjectName("num10")
        self.horizontalLayout10.addWidget(self.num10)
        self.verticalLayout10 = QtWidgets.QVBoxLayout()
        self.verticalLayout10.setSpacing(0)
        self.verticalLayout10.setObjectName("verticalLayout10")
        self.name10 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name10.sizePolicy().hasHeightForWidth())
        self.name10.setSizePolicy(sizePolicy)
        self.name10.setStyleSheet("")
        self.name10.setText("")
        self.name10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name10.setObjectName("name10")
        self.verticalLayout10.addWidget(self.name10)
        self.pickups10 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups10.sizePolicy().hasHeightForWidth())
        self.pickups10.setSizePolicy(sizePolicy)
        self.pickups10.setStyleSheet("")
        self.pickups10.setText("")
        self.pickups10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups10.setObjectName("pickups10")
        self.verticalLayout10.addWidget(self.pickups10)
        self.line10 = QtWidgets.QFrame(self.layoutWidget)
        self.line10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line10.setObjectName("line10")
        self.verticalLayout10.addWidget(self.line10)
        self.horizontalLayout10.addLayout(self.verticalLayout10)
        self.gridLayout_4.addLayout(self.horizontalLayout10, 4, 2, 1, 1)
        self.horizontalLayout6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout6.setObjectName("horizontalLayout6")
        self.num6 = QtWidgets.QLabel(self.layoutWidget)
        self.num6.setMinimumSize(QtCore.QSize(120, 120))
        self.num6.setMaximumSize(QtCore.QSize(120, 120))
        self.num6.setStyleSheet("")
        self.num6.setAlignment(QtCore.Qt.AlignCenter)
        self.num6.setObjectName("num6")
        self.horizontalLayout6.addWidget(self.num6)
        self.verticalLayout6 = QtWidgets.QVBoxLayout()
        self.verticalLayout6.setSpacing(0)
        self.verticalLayout6.setObjectName("verticalLayout6")
        self.name6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name6.sizePolicy().hasHeightForWidth())
        self.name6.setSizePolicy(sizePolicy)
        self.name6.setStyleSheet("")
        self.name6.setText("")
        self.name6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name6.setObjectName("name6")
        self.verticalLayout6.addWidget(self.name6)
        self.pickups6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups6.sizePolicy().hasHeightForWidth())
        self.pickups6.setSizePolicy(sizePolicy)
        self.pickups6.setStyleSheet("")
        self.pickups6.setText("")
        self.pickups6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups6.setObjectName("pickups6")
        self.verticalLayout6.addWidget(self.pickups6)
        self.line6 = QtWidgets.QFrame(self.layoutWidget)
        self.line6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line6.setObjectName("line6")
        self.verticalLayout6.addWidget(self.line6)
        self.horizontalLayout6.addLayout(self.verticalLayout6)
        self.gridLayout_4.addLayout(self.horizontalLayout6, 0, 2, 1, 1)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.num1 = QtWidgets.QLabel(self.layoutWidget)
        self.num1.setStyleSheet("background-color: rgb(255, 192, 0);")
        self.num1.setAlignment(QtCore.Qt.AlignCenter)
        self.num1.setObjectName("num1")
        self.horizontalLayout1.addWidget(self.num1)
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setSpacing(0)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.name1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name1.sizePolicy().hasHeightForWidth())
        self.name1.setSizePolicy(sizePolicy)
        self.name1.setStyleSheet("")
        self.name1.setText("")
        self.name1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name1.setObjectName("name1")
        self.verticalLayout1.addWidget(self.name1)
        self.pickups1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups1.sizePolicy().hasHeightForWidth())
        self.pickups1.setSizePolicy(sizePolicy)
        self.pickups1.setStyleSheet("")
        self.pickups1.setText("")
        self.pickups1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups1.setObjectName("pickups1")
        self.verticalLayout1.addWidget(self.pickups1)
        self.line1 = QtWidgets.QFrame(self.layoutWidget)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.verticalLayout1.addWidget(self.line1)
        self.horizontalLayout1.addLayout(self.verticalLayout1)
        self.gridLayout_4.addLayout(self.horizontalLayout1, 0, 0, 1, 1)
        self.horizontalLayout3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.num3 = QtWidgets.QLabel(self.layoutWidget)
        self.num3.setStyleSheet("background-color: rgb(237, 125, 49);")
        self.num3.setAlignment(QtCore.Qt.AlignCenter)
        self.num3.setObjectName("num3")
        self.horizontalLayout3.addWidget(self.num3)
        self.verticalLayout3 = QtWidgets.QVBoxLayout()
        self.verticalLayout3.setSpacing(0)
        self.verticalLayout3.setObjectName("verticalLayout3")
        self.name3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name3.sizePolicy().hasHeightForWidth())
        self.name3.setSizePolicy(sizePolicy)
        self.name3.setStyleSheet("")
        self.name3.setText("")
        self.name3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name3.setObjectName("name3")
        self.verticalLayout3.addWidget(self.name3)
        self.pickups3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups3.sizePolicy().hasHeightForWidth())
        self.pickups3.setSizePolicy(sizePolicy)
        self.pickups3.setStyleSheet("")
        self.pickups3.setText("")
        self.pickups3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups3.setObjectName("pickups3")
        self.verticalLayout3.addWidget(self.pickups3)
        self.line3 = QtWidgets.QFrame(self.layoutWidget)
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.verticalLayout3.addWidget(self.line3)
        self.horizontalLayout3.addLayout(self.verticalLayout3)
        self.gridLayout_4.addLayout(self.horizontalLayout3, 2, 0, 1, 1)
        self.horizontalLayout4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.num4 = QtWidgets.QLabel(self.layoutWidget)
        self.num4.setStyleSheet("")
        self.num4.setAlignment(QtCore.Qt.AlignCenter)
        self.num4.setObjectName("num4")
        self.horizontalLayout4.addWidget(self.num4)
        self.verticalLayout4 = QtWidgets.QVBoxLayout()
        self.verticalLayout4.setSpacing(0)
        self.verticalLayout4.setObjectName("verticalLayout4")
        self.name4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name4.sizePolicy().hasHeightForWidth())
        self.name4.setSizePolicy(sizePolicy)
        self.name4.setStyleSheet("")
        self.name4.setText("")
        self.name4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name4.setObjectName("name4")
        self.verticalLayout4.addWidget(self.name4)
        self.pickups4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickups4.sizePolicy().hasHeightForWidth())
        self.pickups4.setSizePolicy(sizePolicy)
        self.pickups4.setStyleSheet("")
        self.pickups4.setText("")
        self.pickups4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pickups4.setObjectName("pickups4")
        self.verticalLayout4.addWidget(self.pickups4)
        self.line4 = QtWidgets.QFrame(self.layoutWidget)
        self.line4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line4.setObjectName("line4")
        self.verticalLayout4.addWidget(self.line4)
        self.horizontalLayout4.addLayout(self.verticalLayout4)
        self.gridLayout_4.addLayout(self.horizontalLayout4, 3, 0, 1, 1)
        self.stackedPages.addWidget(self.pageBoard)
        self.buttonLogout = QtWidgets.QPushButton(self.mainPage)
        self.buttonLogout.setGeometry(QtCore.QRect(70, 960, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.buttonLogout.setFont(font)
        self.buttonLogout.setStyleSheet("")
        self.buttonLogout.setObjectName("buttonLogout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.mainPage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 340, 222, 411))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.buttonsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.buttonsLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.radioAI = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioAI.setStyleSheet("QRadioButton {\n"
"    font: 16pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  50px;\n"
"    height:                 50px;\n"
"    border-radius:          27px;\n"
"    image: url(resources/aiicon.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(206, 121, 107);\n"
"    border: 2px solid rgb(206, 121, 107);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: black;\n"
"    border: 2px solid;\n"
"}")
        self.radioAI.setObjectName("radioAI")
        self.buttonsLayout.addWidget(self.radioAI)
        self.radioManual = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioManual.setStyleSheet("QRadioButton {\n"
"    font: 16pt \"Nirmala UI\";\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  50px;\n"
"    height:                 50px;\n"
"    border-radius:          27px;\n"
"    image: url(resources/maunalicon.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(206, 121, 107);\n"
"    border: 2px solid rgb(206, 121, 107);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: black;\n"
"    border: 2px solid;\n"
"}")
        self.radioManual.setObjectName("radioManual")
        self.buttonsLayout.addWidget(self.radioManual)
        self.radioBoard = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioBoard.setStyleSheet("QRadioButton {\n"
"    font: 16pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  50px;\n"
"    height:                 50px;\n"
"    border-radius:          27px;\n"
"    image: url(resources/vsicon.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(206, 121, 107);\n"
"    border: 2px solid rgb(206, 121, 107);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: black;\n"
"    border: 2px solid;\n"
"}")
        self.radioBoard.setObjectName("radioBoard")
        self.buttonsLayout.addWidget(self.radioBoard)
        self.radioInteraction = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioInteraction.setStyleSheet("QRadioButton {\n"
"    font: 16pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  50px;\n"
"    height:                 50px;\n"
"    border-radius:          27px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(206, 121, 107);\n"
"    border: 2px solid rgb(206, 121, 107);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: black;\n"
"    border: 2px solid;\n"
"}")
        self.radioInteraction.setObjectName("radioInteraction")
        self.buttonsLayout.addWidget(self.radioInteraction)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.mainPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 220, 221, 59))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.userInfoLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.userInfoLayout.setContentsMargins(0, 0, 0, 0)
        self.userInfoLayout.setSpacing(0)
        self.userInfoLayout.setObjectName("userInfoLayout")
        self.labelRole = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelRole.setStyleSheet("font: 14pt \"Nirmala UI\";\n"
"color: rgb(93, 93, 93);")
        self.labelRole.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRole.setObjectName("labelRole")
        self.userInfoLayout.addWidget(self.labelRole)
        self.labelUsername_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelUsername_2.setStyleSheet("font: 18pt \"Nirmala UI\";")
        self.labelUsername_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUsername_2.setObjectName("labelUsername_2")
        self.userInfoLayout.addWidget(self.labelUsername_2)
        self.sidebarBackground = QtWidgets.QLabel(self.mainPage)
        self.sidebarBackground.setGeometry(QtCore.QRect(0, 0, 311, 1081))
        self.sidebarBackground.setStyleSheet("background-color: #E7AD99;")
        self.sidebarBackground.setText("")
        self.sidebarBackground.setScaledContents(False)
        self.sidebarBackground.setObjectName("sidebarBackground")
        self.label = QtWidgets.QLabel(self.mainPage)
        self.label.setGeometry(QtCore.QRect(80, 80, 151, 121))
        self.label.setStyleSheet("image: url(resources/usericon.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.sidebarBackground.raise_()
        self.stackedPages.raise_()
        self.buttonLogout.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.label.raise_()
        self.stackedLogin.addWidget(self.mainPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedLogin.setCurrentIndex(1)
        self.stackedPages.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textUsername, self.textPassword)
        MainWindow.setTabOrder(self.textPassword, self.buttonLogin)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonLogin.setText(_translate("MainWindow", "Log in"))
        self.labelPassword.setText(_translate("MainWindow", "Password"))
        self.labelLoginError.setText(_translate("MainWindow", "Invalid username or password"))
        self.labelUsername.setText(_translate("MainWindow", "Username"))
        self.labelLogin.setText(_translate("MainWindow", "Log in"))
        self.pageAI.setProperty("class", _translate("MainWindow", "pagebackground"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.buttonStop.setText(_translate("MainWindow", "Stop"))
        self.Titel.setText(_translate("MainWindow", "Shakeit AI Control Panel"))
        self.statusBox.setTitle(_translate("MainWindow", "Status"))
        self.settingsBox.setTitle(_translate("MainWindow", "Setttings"))
        self.buttonSettings.setText(_translate("MainWindow", "Change settings"))
        self.labelIterations.setText(_translate("MainWindow", "Iterations:"))
        self.pageManual.setProperty("class", _translate("MainWindow", "pagebackground"))
        self.Titel_2.setText(_translate("MainWindow", "Shakeit Manual Control Panel"))
        self.labelForward.setText(_translate("MainWindow", "Forward"))
        self.fw_r1s2.setText(_translate("MainWindow", "Repetitions:1, Speed: 2"))
        self.fw_r3s2.setText(_translate("MainWindow", "Repetitions:3, Speed: 2"))
        self.fw_r1s4.setText(_translate("MainWindow", "Repetitions:1, Speed: 4"))
        self.fw_r3s4.setText(_translate("MainWindow", "Repetitions:3, Speed: 4"))
        self.fw_r1s6.setText(_translate("MainWindow", "Repetitions:1, Speed: 6"))
        self.fw_r3s6.setText(_translate("MainWindow", "Repetitions:3, Speed: 6"))
        self.fw_r1s8.setText(_translate("MainWindow", "Repetitions:1, Speed: 8"))
        self.fw_r3s8.setText(_translate("MainWindow", "Repetitions:3, Speed: 8"))
        self.fw_r1s10.setText(_translate("MainWindow", "Repetitions:1, Speed: 10"))
        self.fw_r3s10.setText(_translate("MainWindow", "Repetitions:3, Speed: 10"))
        self.labelBackward.setText(_translate("MainWindow", "Backward"))
        self.b_r1s2.setText(_translate("MainWindow", "Repetitions:1, Speed: 2"))
        self.b_r3s2.setText(_translate("MainWindow", "Repetitions:3, Speed: 2"))
        self.b_r1s4.setText(_translate("MainWindow", "Repetitions:1, Speed: 4"))
        self.b_r3s4.setText(_translate("MainWindow", "Repetitions:3, Speed: 4"))
        self.b_r1s6.setText(_translate("MainWindow", "Repetitions:1, Speed: 6"))
        self.b_r3s6.setText(_translate("MainWindow", "Repetitions:3, Speed: 6"))
        self.b_r1s8.setText(_translate("MainWindow", "Repetitions:1, Speed: 8"))
        self.b_r3s8.setText(_translate("MainWindow", "Repetitions:3, Speed: 8"))
        self.b_r1s10.setText(_translate("MainWindow", "Repetitions:1, Speed: 10"))
        self.b_r3s10.setText(_translate("MainWindow", "Repetitions:3, Speed: 10"))
        self.labelFlip.setText(_translate("MainWindow", "Flip"))
        self.fp_r1s2.setText(_translate("MainWindow", "Repetitions:1, Speed: 2"))
        self.fp_r3s2.setText(_translate("MainWindow", "Repetitions:3, Speed: 2"))
        self.fp_r1s4.setText(_translate("MainWindow", "Repetitions:1, Speed: 4"))
        self.fp_r3s4.setText(_translate("MainWindow", "Repetitions:3, Speed: 4"))
        self.fp_r1s6.setText(_translate("MainWindow", "Repetitions:1, Speed: 6"))
        self.fp_r3s6.setText(_translate("MainWindow", "Repetitions:3, Speed: 6"))
        self.fp_r1s8.setText(_translate("MainWindow", "Repetitions:1, Speed: 8"))
        self.fp_r3s8.setText(_translate("MainWindow", "Repetitions:3, Speed: 8"))
        self.fp_r1s10.setText(_translate("MainWindow", "Repetitions:1, Speed: 10"))
        self.fp_r3s10.setText(_translate("MainWindow", "Repetitions:3, Speed: 10"))
        self.pageBoard.setProperty("class", _translate("MainWindow", "pagebackground"))
        self.Titel_3.setText(_translate("MainWindow", "Leaderboard"))
        self.num7.setText(_translate("MainWindow", "7"))
        self.num7.setProperty("class", _translate("MainWindow", "board_num"))
        self.num9.setText(_translate("MainWindow", "9"))
        self.num9.setProperty("class", _translate("MainWindow", "board_num"))
        self.num8.setText(_translate("MainWindow", "8"))
        self.num8.setProperty("class", _translate("MainWindow", "board_num"))
        self.num2.setText(_translate("MainWindow", "2"))
        self.num2.setProperty("class", _translate("MainWindow", "board_num"))
        self.num5.setText(_translate("MainWindow", "5"))
        self.num5.setProperty("class", _translate("MainWindow", "board_num"))
        self.num10.setText(_translate("MainWindow", "10"))
        self.num10.setProperty("class", _translate("MainWindow", "board_num"))
        self.num6.setText(_translate("MainWindow", "6"))
        self.num6.setProperty("class", _translate("MainWindow", "board_num"))
        self.num1.setText(_translate("MainWindow", "1"))
        self.num1.setProperty("class", _translate("MainWindow", "board_num"))
        self.num3.setText(_translate("MainWindow", "3"))
        self.num3.setProperty("class", _translate("MainWindow", "board_num"))
        self.num4.setText(_translate("MainWindow", "4"))
        self.num4.setProperty("class", _translate("MainWindow", "board_num"))
        self.buttonLogout.setText(_translate("MainWindow", "Log out"))
        self.radioAI.setText(_translate("MainWindow", " AI Control"))
        self.radioManual.setText(_translate("MainWindow", "Manual Control"))
        self.radioBoard.setText(_translate("MainWindow", "Leaderboard"))
        self.radioInteraction.setText(_translate("MainWindow", "Interaction"))
        self.labelRole.setText(_translate("MainWindow", "Role"))
        self.labelUsername_2.setText(_translate("MainWindow", "Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
